// Generated by `pnpm tokens:build` from tokens.json — do not edit.
export const themeColors = {
  light: { 'background': '#fdfaf5', 'surface': '#ffffff', 'surface-selected': '#f3f0ea', 'foreground': '#262420', 'muted': '#6f6b64', 'border': '#e2dfd9', 'primary': '#ffd78b', 'primary-foreground': '#262420', 'primary-emphasis': '#8a6500', 'success': '#16813d', 'warning': '#a45300', 'danger': '#b93736' },
  dark: { 'background': '#262420', 'surface': '#3d3a35', 'surface-selected': '#55524c', 'foreground': '#fdfaf5', 'muted': '#a29e96', 'border': '#55524c', 'primary': '#ffd78b', 'primary-foreground': '#262420', 'primary-emphasis': '#f1c570', 'success': '#58b670', 'warning': '#e6802d', 'danger': '#f46f69' },
} as const;

export type ThemeColorName = keyof typeof themeColors.light;
