import type { ImageSource } from 'expo-image';

import type { KidEmotion, KidMember } from '@/api/kid-emotions';

export const EMOTION_PORTRAITS: Record<KidMember, Record<KidEmotion, ImageSource | number>> = {
  regina: {
    happy: require('@/assets/regina/emotions/happy.png'),
    sad: require('@/assets/regina/emotions/sad.png'),
    angry: require('@/assets/regina/emotions/angry.png'),
    scared: require('@/assets/regina/emotions/scared.png'),
    surprised: require('@/assets/regina/emotions/surprised.png'),
    disgusted: require('@/assets/regina/emotions/disgusted.png'),
    excited: require('@/assets/regina/emotions/excited.png'),
    proud: require('@/assets/regina/emotions/proud.png'),
    loved: require('@/assets/regina/emotions/loved.png'),
    grateful: require('@/assets/regina/emotions/grateful.png'),
    calm: require('@/assets/regina/emotions/calm.png'),
    hopeful: require('@/assets/regina/emotions/hopeful.png'),
    curious: require('@/assets/regina/emotions/curious.png'),
    playful: require('@/assets/regina/emotions/playful.png'),
    bored: require('@/assets/regina/emotions/bored.png'),
    tired: require('@/assets/regina/emotions/tired.png'),
    nervous: require('@/assets/regina/emotions/nervous.png'),
    confused: require('@/assets/regina/emotions/confused.png'),
    frustrated: require('@/assets/regina/emotions/frustrated.png'),
    worried: require('@/assets/regina/emotions/worried.png'),
    lonely: require('@/assets/regina/emotions/lonely.png'),
    disappointed: require('@/assets/regina/emotions/disappointed.png'),
    jealous: require('@/assets/regina/emotions/jealous.png'),
    embarrassed: require('@/assets/regina/emotions/embarrassed.png'),
  },
  andres: {
    happy: require('@/assets/andres/emotions/happy.png'),
    sad: require('@/assets/andres/emotions/sad.png'),
    angry: require('@/assets/andres/emotions/angry.png'),
    scared: require('@/assets/andres/emotions/scared.png'),
    surprised: require('@/assets/andres/emotions/surprised.png'),
    disgusted: require('@/assets/andres/emotions/disgusted.png'),
    excited: require('@/assets/andres/emotions/excited.png'),
    proud: require('@/assets/andres/emotions/proud.png'),
    loved: require('@/assets/andres/emotions/loved.png'),
    grateful: require('@/assets/andres/emotions/grateful.png'),
    calm: require('@/assets/andres/emotions/calm.png'),
    hopeful: require('@/assets/andres/emotions/hopeful.png'),
    curious: require('@/assets/andres/emotions/curious.png'),
    playful: require('@/assets/andres/emotions/playful.png'),
    bored: require('@/assets/andres/emotions/bored.png'),
    tired: require('@/assets/andres/emotions/tired.png'),
    nervous: require('@/assets/andres/emotions/nervous.png'),
    confused: require('@/assets/andres/emotions/confused.png'),
    frustrated: require('@/assets/andres/emotions/frustrated.png'),
    worried: require('@/assets/andres/emotions/worried.png'),
    lonely: require('@/assets/andres/emotions/lonely.png'),
    disappointed: require('@/assets/andres/emotions/disappointed.png'),
    jealous: require('@/assets/andres/emotions/jealous.png'),
    embarrassed: require('@/assets/andres/emotions/embarrassed.png'),
  },
};
