// AUTO-GENERATED by `pnpm routes:generate`. Do not edit by hand.
import type { Config } from 'ziggy-js';

export declare const Ziggy: Config;

declare module 'ziggy-js' {
  interface RouteList {
    "api.status": [],
    "api.auth.apple": [],
    "api.auth.logout": [],
    "api.user": [],
    "api.moods.index": [],
    "api.moods.update": [
        {
            "name": "member",
            "required": true
        }
    ],
    "api.push-tokens.store": [],
    "api.notifications.test": [],
    "api.kids.behaviors.index": [
        {
            "name": "member",
            "required": true
        }
    ],
    "api.behaviors.store": [],
    "api.behaviors.update": [
        {
            "name": "behavior",
            "required": true,
            "binding": "id"
        }
    ],
    "api.behaviors.destroy": [
        {
            "name": "behavior",
            "required": true,
            "binding": "id"
        }
    ],
    "api.behaviors.logs.store": [
        {
            "name": "behavior",
            "required": true,
            "binding": "id"
        }
    ],
    "api.behavior-logs.index": [],
    "api.behavior-logs.destroy": [
        {
            "name": "behaviorLog",
            "required": true,
            "binding": "id"
        }
    ],
    "api.behavior-illustrations.store": [],
    "api.behavior-illustrations.show": [
        {
            "name": "behaviorIllustration",
            "required": true,
            "binding": "id"
        }
    ],
    "api.temp-files.presign": [],
    "api.articles.index": [],
    "api.articles.show": [
        {
            "name": "article",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.draft_articles.slugs": [],
    "api.draft_articles.show": [
        {
            "name": "article",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.projects.index": [],
    "api.resume": [],
    "api.resume.pdf": [],
    "api.contact": [],
    "api.typo": [],
    "api.slug-history.index": []
}
}
export {};
