// AUTO-GENERATED by `pnpm routes:generate`. Do not edit by hand.
import type { Config } from 'ziggy-js';

export declare const Ziggy: Config;

declare module 'ziggy-js' {
  interface RouteList {
    "api.status": [],
    "api.auth.apple": [],
    "api.auth.logout": [],
    "api.user": [],
    "api.moods.index": [],
    "api.moods.update": [
        {
            "name": "member",
            "required": true
        }
    ],
    "api.articles.index": [],
    "api.articles.show": [
        {
            "name": "article",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.draft_articles.slugs": [],
    "api.draft_articles.show": [
        {
            "name": "article",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.projects.index": [],
    "api.resume": [],
    "api.resume.pdf": [],
    "api.contact": [],
    "api.typo": [],
    "api.slug-history.index": []
}
}
export {};
