<?php

use App\Models\Assistant;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    /**
     * The illustrator "mini app". One-time data migration — from here on it
     * is managed from Nova like the other assistants.
     */
    public function up(): void
    {
        // Tests build the exact data they need; skip so counts stay predictable.
        if (app()->environment('testing')) {
            return;
        }

        Assistant::firstOrCreate(['slug' => 'illustrator'], [
            'kind' => Assistant::KIND_ILLUSTRATOR,
            'name' => 'Illustrator',
            'emoji' => '🎨',
            'description' => 'Draw anything in the family style',
            // Illustrator replies are generated by the Illustrator service,
            // not by a text model; these instructions are documentation only.
            'instructions' => 'Generates illustrations in the family visual language. '
                .'Pick who appears in the drawing and describe the scene; follow-up messages edit the previous image.',
            'members' => ['alfonso', 'saida'],
            'copyable_output' => false,
            'sort_order' => 2,
        ]);
    }

    public function down(): void
    {
        Assistant::where('slug', 'illustrator')->forceDelete();
    }
};
