// Generates color tokens from the single source of truth (`tokens.json`).
// Run with `pnpm tokens:build`.
//
// Outputs:
//   - tailwind.tokens.cjs      → color object for the Tailwind config
//   - src/global.css           → CSS vars as `R G B` triplets (NativeWind)
//   - src/constants/colors.gen.ts → hex values for native props (SymbolView tint, tab bar, etc.)
//
// Each generated block lives between `/* @tokens:<name>:start|end */` markers;
// everything outside the markers is left untouched.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(join(ROOT, 'tokens.json'), 'utf8'));
const { scales, semantic } = tokens;

function resolve(value) {
  if (value.startsWith('#')) {
    return value;
  }
  const [family, step] = value.split('.');
  return scales[family][step];
}

function hexToTriplet(hex) {
  const n = parseInt(hex.slice(1), 16);
  return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`;
}

const scaleEntries = Object.entries(scales).flatMap(([family, steps]) =>
  Object.entries(steps).map(([step, hex]) => [`${family}-${step}`, hex]),
);
const lightEntries = Object.entries(semantic.light).map(([name, ref]) => [name, resolve(ref)]);
const darkEntries = Object.entries(semantic.dark).map(([name, ref]) => [name, resolve(ref)]);

// --- tailwind.tokens.cjs ---
const v = (name) => `'rgb(var(--color-${name}) / <alpha-value>)'`;
const scaleObject = (family) =>
  `{ ${Object.keys(scales[family])
    .map((s) => `'${s}': ${v(`${family}-${s}`)}`)
    .join(', ')} }`;

const semanticNames = Object.keys(semantic.light);
const cjs = `// Generated by \`pnpm tokens:build\` from tokens.json — do not edit.
module.exports = {
  gold: ${scaleObject('gold')},
  neutral: ${scaleObject('neutral')},
  success: ${scaleObject('success')},
  warning: ${scaleObject('warning')},
  danger: ${scaleObject('danger')},
${semanticNames.map((name) => `  '${name}': ${v(name)},`).join('\n')}
};
`;
writeFileSync(join(ROOT, 'tailwind.tokens.cjs'), cjs);

// --- src/global.css (R G B triplets) ---
const mobileLight = [
  ...scaleEntries.map(([name, hex]) => `--color-${name}: ${hexToTriplet(hex)};`),
  ...lightEntries.map(([name, hex]) => `--color-${name}: ${hexToTriplet(hex)};`),
]
  .map((line) => `    ${line}`)
  .join('\n');
const mobileDark = darkEntries
  .map(([name, hex]) => `      --color-${name}: ${hexToTriplet(hex)};`)
  .join('\n');

const globalPath = join(ROOT, 'src/global.css');
let globalCss = readFileSync(globalPath, 'utf8');
globalCss = globalCss.replace(
  /\/\* @tokens:light:start \*\/[\s\S]*?\/\* @tokens:light:end \*\//,
  `/* @tokens:light:start */\n${mobileLight}\n    /* @tokens:light:end */`,
);
globalCss = globalCss.replace(
  /\/\* @tokens:dark:start \*\/[\s\S]*?\/\* @tokens:dark:end \*\//,
  `/* @tokens:dark:start */\n${mobileDark}\n      /* @tokens:dark:end */`,
);
writeFileSync(globalPath, globalCss);

// --- src/constants/colors.gen.ts (hex values for native props) ---
const tsObject = (entries) =>
  `{ ${entries.map(([name, hex]) => `'${name}': '${hex}'`).join(', ')} }`;
const tsContent = `// Generated by \`pnpm tokens:build\` from tokens.json — do not edit.
export const themeColors = {
  light: ${tsObject(lightEntries)},
  dark: ${tsObject(darkEntries)},
} as const;

export type ThemeColorName = keyof typeof themeColors.light;
`;
writeFileSync(join(ROOT, 'src/constants/colors.gen.ts'), tsContent);

console.log('✓ tokens built → tailwind.tokens.cjs, src/global.css, src/constants/colors.gen.ts');
