#!/usr/bin/env node
// Generates typed Ziggy route definitions from the Laravel API into the app.
// Run with `pnpm routes:generate` after adding or renaming an `api.*` route.
import { spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const appDir = resolve(here, '..');
const apiDir = resolve(appDir, '..', 'api');
const outDir = resolve(appDir, 'src', 'api');

const tmpRel = 'storage/app/ziggy.tmp.js';
const tmpJs = resolve(apiDir, tmpRel);
const tmpDts = tmpJs.replace(/\.js$/, '.d.ts');

const jsOut = resolve(outDir, 'ziggy.gen.js');
const dtsOut = resolve(outDir, 'ziggy.gen.d.ts');

const banner = '// AUTO-GENERATED by `pnpm routes:generate`. Do not edit by hand.\n';

const result = spawnSync('php', ['artisan', 'ziggy:generate', tmpRel, '--types'], {
  cwd: apiDir,
  stdio: 'inherit',
});

if (result.status !== 0) {
  process.exit(result.status ?? 1);
}

mkdirSync(outDir, { recursive: true });

// The app supplies the API origin at runtime, so strip the build-time host.
const js = readFileSync(tmpJs, 'utf8');
const match = js.match(/const Ziggy = (\{.*?\});\s*(?:\n|$)/s);
if (!match) {
  console.error('Failed to extract Ziggy config from generated file');
  process.exit(1);
}
const ziggy = JSON.parse(match[1]);
ziggy.url = '';
ziggy.port = null;

writeFileSync(jsOut, `${banner}export const Ziggy = ${JSON.stringify(ziggy)};\n`, 'utf8');

// Keep Ziggy's RouteList augmentation for type-safe route names and params,
// and declare the shape of the generated JS export.
const dts = readFileSync(tmpDts, 'utf8').replace('/* This file is generated by Ziggy. */\n', '');
writeFileSync(
  dtsOut,
  `${banner}import type { Config } from 'ziggy-js';\n\nexport declare const Ziggy: Config;\n\n${dts}`,
  'utf8',
);

rmSync(tmpJs, { force: true });
rmSync(tmpDts, { force: true });

console.log(`Wrote ${jsOut}`);
console.log(`Wrote ${dtsOut}`);
